import PropTypes from "prop-types";
import styles from "../subpage/SubPage.module.css"

const IetfStatistics = () => {
    return (
        <div>
            <h1>
                Statistics for IETF-related Requests
            </h1>
            <h2>
                Reports
            </h2>
            <table>
                <tbody>
                <tr>
                    <th>
                        Year
                    </th>
                    <th colSpan="12">
                        Monthly Reports
                    </th>
                </tr>
                <tr>
                    <td>
                        2025
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        2024
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2023
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2022
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2021
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2020
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2019
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2018
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2017
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2016
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2015
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2014
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2013
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2012
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2011
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2010
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2009
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2008
                    </td>
                    <td>
                        Jan
                    </td>
                    <td>
                        Feb
                    </td>
                    <td>
                        Mar
                    </td>
                    <td>
                        Apr
                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                <tr>
                    <td>
                        2007
                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>
                        May
                    </td>
                    <td>
                        Jun
                    </td>
                    <td>
                        Jul
                    </td>
                    <td>
                        Aug
                    </td>
                    <td>
                        Sep
                    </td>
                    <td>
                        Oct
                    </td>
                    <td>
                        Nov
                    </td>
                    <td>
                        Dec
                    </td>
                </tr>
                </tbody>
            </table>
            <h2>
                Methodology
            </h2>
            <p>
                The statistics presented on this website were gathered by extracting data from our ticketing system
                queues into daily logs for each queue that are then concatenated into monthly logs for each queue.
            </p>
            <p>
                The logs were then processed extract the transaction history for each ticket in each queue, from the
                date the ticket was opened until the date the ticket was closed, or the end of the monthly log for
                tickets not yet closed.
            </p>
            <p>
                The number of open tickets, closed tickets, the amount of time spent in each of IANA processing, Other,
                and Requestor related states (for which transaction data is available), and the total elapsed time from
                ticket open to close (or the end of the present reporting period), as well as the mean processing time,
                median processing, and standard deviation from the mean processing time is presented.
            </p>
            <h2>
                Definitions
            </h2>
            <p>
                Below are tables containing the definitions for the queues in which we track IETF-related requests.
            </p>
            <h3>
                Definitions for Internet Draft Processing
            </h3>
            <p>
                This refers to queues for Internet Drafts in Last Call (drafts-lastcall), Evaluation (drafts-eval),
                Approved by the IESG (drafts-approved), and drafts requiring references to be updated
                (drafts-update-refs).
            </p>
            <p>

            </p>
            <table>
                <thead>
                <tr>
                    <th>
                        State
                    </th>
                    <th>
                        Description
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Created
                    </td>
                    <td>
                        A request is created when we receive either a notification from the IETF Secretariat that a
                        document has been approved by the IESG for publication as an RFC OR when the RFC-Editor notifies
                        us that they intend to publish a document as an RFC.
                    </td>
                </tr>
                <tr>
                    <td>
                        Resolved
                    </td>
                    <td>
                        A request is resolved when the RFC-Editor confirms that they have received our notification of
                        completed actions for the document OR when we confirm that there are no IANA Considerations.
                    </td>
                </tr>
                <tr>
                    <td>
                        Processing Time
                    </td>
                    <td>
                        The number of calendar days between the date the ticket was Created and Resolved. If a ticket is
                        not yet resolved, Processing Time is the number of workdays between the date the ticket was
                        created and the last date of the reporting period.
                    </td>
                </tr>
                </tbody>
            </table>
            <p>

            </p>
            <h3>
                Definitions for Protocol Assignments
            </h3>
            <p>
                This refers to queues for New Port Assignments (iana-ports), Modifications to Port Assignments
                (port-modifications), Multicast IP Address registrations (iana-multicast), IANA TRIP ITAD Registrations
                (iana-trip), Media Type Registrations (iana-mime), and all other protocol parameters (iana-prot-param).
            </p>
            <p>

            </p>
            <table>
                <thead>
                <tr>
                    <th>
                        State
                    </th>
                    <th>
                        Description
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Created
                    </td>
                    <td>
                        A request is created when the user has submitted a template, web form or email.
                    </td>
                </tr>
                <tr>
                    <td>
                        Resolved
                    </td>
                    <td>
                        A request is resolved when the ticket is closed either because the requested resource has been
                        assigned, the resource registration has been modified or deleted as requested or the ticket has
                        either been administratively closed or withdrawn by the requester.
                    </td>
                </tr>
                <tr>
                    <td>
                        Rejected
                    </td>
                    <td>
                        The request was inappropriate or could not be met for policy reasons.
                    </td>
                </tr>
                <tr>
                    <td>
                        Processing Time
                    </td>
                    <td>
                        The number of calendar days between the date the ticket was Created and Resolved. If a ticket is
                        not yet resolved, Processing Time is the number of workdays between the date the ticket was
                        created and the last date of the reporting period.
                    </td>
                </tr>
                </tbody>
            </table>
            <p>

            </p>
            <h3>
                Attribution of responsibility
            </h3>
            <p>
                In our processing, we attribute time to various responsible parties, divided into these categories.
            </p>
            <p>

            </p>
            <table>
                <thead>
                <tr>
                    <th>
                        State
                    </th>
                    <th>
                        Description
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        IANA
                    </td>
                    <td>
                        This includes the time we spent working on the request
                    </td>
                </tr>
                <tr>
                    <td>
                        Third party
                    </td>
                    <td>
                        This includes time spent with the designated expert, IESG, Authors, Working Group Chairs,
                        RFC-Editor or other outside party
                    </td>
                </tr>
                <tr>
                    <td>
                        Requestor
                    </td>
                    <td>
                        This includes the time the request is with the requester. For the case of drafts-lastcall,
                        drafts-eval, drafts-approval and drafts-update-refs queues, the requestor is either the IESG or
                        the RFC-Editor so there is no “requestor time”.
                    </td>
                </tr>
                <tr>
                    <td>
                        Zombie
                    </td>
                    <td>
                        This state appears if the ticket was created prior to January 1, 2007 and no state was known or
                        given at the time these statistics were being tracked. Those with this state do not exist as all
                        tickets created before January 1 have been resolved.
                    </td>
                </tr>
                </tbody>
            </table>
            <p>

            </p>

        </div>
    );
};

IetfStatistics.propTypes = {}

export default IetfStatistics;
